#!/bin/bash
# Debug script for checking test setup

echo "=== Quick Debugging Guide ==="
echo ""
echo "1. Check all containers are running:"
echo "   docker ps"
echo ""
echo "2. Check Kafka Lag Exporter metrics:"
echo "   curl -s http://localhost:8000/metrics | grep kafka_consumergroup_group_lag | grep test-consumer-group"
echo ""
echo "3. Check Prometheus has the metrics:"
echo "   curl -s 'http://localhost:9090/api/v1/query?query=kafka_consumergroup_group_lag'"
echo ""
echo "4. View Kafka Lag Exporter logs:"
echo "   docker logs kafka-lag-exporter | tail -20"
echo ""
echo "5. View Prometheus logs:"
echo "   docker logs prometheus | tail -20"
echo ""
echo "6. Generate more lag:"
echo "   docker compose -p kafka-lag-exporter-test -f test/docker-compose.local.yaml exec -T kafka kafka-producer-perf-test --topic test-lag-topic --num-records 100 --record-size 1000 --throughput -1 --producer-props bootstrap.servers=localhost:9092"
echo ""
echo "7. Check consumer groups:"
echo "   docker compose -p kafka-lag-exporter-test -f test/docker-compose.local.yaml exec -T kafka kafka-consumer-groups --bootstrap-server localhost:9092 --list"
echo ""
